package com.api.model;
// Generated 2018-9-1 19:35:49 by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.base.framework.model.BaseModel;

/**
 * DiyFormField generated by hbm2java
 */
@Entity
@Table(name = "diy_form_field")
public class DiyFormField extends BaseModel {

	private static final long serialVersionUID = 1373509753483320580L;
	private Integer fieldId;
	private Integer formId;
	private String fieldCode;
	private String fieldText;
	private Integer displayOrder;

	public DiyFormField() {
	}

	public DiyFormField(Integer formId, String fieldText) {
		this.formId = formId;
		this.fieldText = fieldText;
	}

	public DiyFormField(Integer formId, String fieldCode, String fieldText, Integer displayOrder) {
		this.formId = formId;
		this.fieldCode = fieldCode;
		this.fieldText = fieldText;
		this.displayOrder = displayOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FIELD_ID", unique = true, nullable = false)
	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	@Column(name = "FORM_ID", nullable = false)
	public Integer getFormId() {
		return this.formId;
	}

	public void setFormId(Integer formId) {
		this.formId = formId;
	}

	@Column(name = "FIELD_CODE", length = 20)
	public String getFieldCode() {
		return this.fieldCode;
	}

	public void setFieldCode(String fieldCode) {
		this.fieldCode = fieldCode;
	}

	@Column(name = "FIELD_TEXT", nullable = false, length = 20)
	public String getFieldText() {
		return this.fieldText;
	}

	public void setFieldText(String fieldText) {
		this.fieldText = fieldText;
	}

	@Column(name = "DISPLAY_ORDER")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

}
