package com.api.model;
// Generated 2018-9-1 19:35:40 by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.base.framework.model.BaseModel;

/**
 * DiyFieldData generated by hbm2java
 */
@Entity
@Table(name = "diy_field_data")
public class DiyFieldData extends BaseModel {

	private static final long serialVersionUID = 7884833346299906216L;
	private Integer dataId;
	private Integer fieldId;
	private String fieldText;
	private String fieldValue;
	private Integer displayOrder;

	public DiyFieldData() {
	}

	public DiyFieldData(Integer fieldId, String fieldValue) {
		this.fieldId = fieldId;
		this.fieldValue = fieldValue;
	}

	public DiyFieldData(Integer fieldId, String fieldText, String fieldValue, Integer displayOrder) {
		this.fieldId = fieldId;
		this.fieldText = fieldText;
		this.fieldValue = fieldValue;
		this.displayOrder = displayOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DATA_ID", unique = true, nullable = false)
	public Integer getDataId() {
		return this.dataId;
	}

	public void setDataId(Integer dataId) {
		this.dataId = dataId;
	}

	@Column(name = "FIELD_ID", nullable = false)
	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	@Column(name = "FIELD_TEXT", length = 400)
	public String getFieldText() {
		return this.fieldText;
	}

	public void setFieldText(String fieldText) {
		this.fieldText = fieldText;
	}

	@Column(name = "FIELD_VALUE", nullable = false, length = 400)
	public String getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	@Column(name = "DISPLAY_ORDER")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

}
