package com.api.model;
// Generated 2018-8-26 12:05:09 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.base.framework.model.BaseModel;

/**
 * DiyForm generated by hbm2java
 */
@Entity
@Table(name = "diy_form")
public class DiyForm extends BaseModel {

	private static final long serialVersionUID = 1640315097798809715L;
	private Integer formId;
	private String formCode;
	private String formName;
	private String comments;
	private Integer formVersion;
	private String formContent;

	public DiyForm() {
	}

	public DiyForm(String formCode, String formName) {
		this.formCode = formCode;
		this.formName = formName;
	}

	public DiyForm(String formCode, String formName, String comments, Integer formVersion, String formContent) {
		this.formCode = formCode;
		this.formName = formName;
		this.comments = comments;
		this.formVersion = formVersion;
		this.formContent = formContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FORM_ID", unique = true, nullable = false)
	public Integer getFormId() {
		return this.formId;
	}

	public void setFormId(Integer formId) {
		this.formId = formId;
	}

	@Column(name = "FORM_CODE", nullable = false, length = 40)
	public String getFormCode() {
		return this.formCode;
	}

	public void setFormCode(String formCode) {
		this.formCode = formCode;
	}

	@Column(name = "FORM_NAME", nullable = false, length = 100)
	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

	@Column(name = "COMMENTS", length = 400)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "FORM_VERSION")
	public Integer getFormVersion() {
		return this.formVersion;
	}

	public void setFormVersion(Integer formVersion) {
		this.formVersion = formVersion;
	}

	@Column(name = "FORM_CONTENT", length = 65535)
	public String getFormContent() {
		return this.formContent;
	}

	public void setFormContent(String formContent) {
		this.formContent = formContent;
	}

}
